print("Getting know you")
print()
myName = input("What is your name? ")
print()
myAge = input("What is your age? ")
print()
myFood = input("What is your favorite food? ")
print()
MyMusic = input("What is your favorite music? ")
print()
myPlace = input("Where do you live? ")
print()
print("You are:")
print(myName)
print("You are " + myAge + " years old.")
print(" Your favorite food is:")
print(myFood)
print("Your favorite music is:")
print(MyMusic)
print("You live in:")
print(myPlace)