print()
print("Tip Calculator. ")
print()
myBill = float(input("How much did you spend? "))
tip = int(input("What percentage do you want to tip? "))
numberOfPeople = int(input("How many people are in your group? "))
print()
myBill = float(input("How much did you spend? "))
tip = int(input("What percentage do you want to tip? "))
numberOfPeople = int(input("How many people are in your group? "))
print("You all owe $", tipsnbill)